### ISSUE TITLE
MUS support?

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#17]
Great player, thanks for it.

Yet one thing it lacks is .mus support, since both libADL and libOPNMIDI can handle it. Would it be possible to add that?

**Comment by jpcima** [comment]
Hello,

yes based on a quick read of the MUS document, this must be probably not too difficult.
I'll add it.

**Comment by freq-mod** [comment]
http://www.shikadi.net/moddingwiki/MUS_Format - comprehensive documentation of the format, hope it helps

**Comment by jpcima** [comment]
Added at 1ffb907
let me know if all is fine.

**Comment by freq-mod** [comment]
Quick test - something seems to be wrong with instrument volumes, some notes are cut short
will update this post with examples later

**Comment by freq-mod** [comment]
[x.zip](https://github.com/jpcima/smf-dsp/files/4896790/x.zip) -  recordings of a file played in SMF-DSP with libOPNMIDI synth, libOPNMIDIplay and .mus file

**Comment by jpcima** [comment]
Ok I adjusted so it produces more or less the same MIDI stream.
There was a state handling problem with velocity, and also a lack of initialization of channel volumes.

**Comment by freq-mod** [comment]
Seems OK now, thanks a lot!
