### ISSUE TITLE
[Feature idea] Ability to change OPL/OPN emulation core

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#18]
Currently, there is no way for that, it uses ADL/OPNMIDI default it seems, while:

ADLMIDI supports three usable emus: Nuked 1.8, DOSBox and JavaOPL3;
OPNMIDI has Nuked OPN2, MAME YM2612, Genesis Plus GX MAME fork, and OPNA FM cores from MAME and Neko Project 2.

**Comment by jpcima** [comment]
This possibility has just been added in 5b4f83a
Here are emulators and respective settings values.

```
    {"dosbox", ADLMIDI_EMU_DOSBOX},
    {"nuked", ADLMIDI_EMU_NUKED},
    {"nuked 1.7", ADLMIDI_EMU_NUKED_174},
    {"opal", ADLMIDI_EMU_OPAL},
    {"java", ADLMIDI_EMU_JAVA},
```

```
    {"mame", OPNMIDI_EMU_MAME},
    {"mame2612", OPNMIDI_EMU_MAME},
    {"nuked", OPNMIDI_EMU_NUKED},
    {"gens", OPNMIDI_EMU_GENS},
    {"gx", OPNMIDI_EMU_GX},
    {"neko", OPNMIDI_EMU_NP2},
    {"mame2608", OPNMIDI_EMU_MAME_2608},
    {"pmdwin", OPNMIDI_EMU_PMDWIN},
```

**Comment by freq-mod** [comment]
What is the difference between `mame` and `mame2612`?

**Comment by jpcima** [comment]
No difference, this is only an alias.
