### ISSUE TITLE
Unable to build under Linux Mint 20.1

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#23]
Running `cmake -DCMAKE_BUILD_TYPE=Release ..` produces:

> -- The C compiler identification is GNU 9.3.0
> -- The CXX compiler identification is GNU 9.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'alsa'
> --   Found alsa, version 1.2.2
> -- Checking for module 'libpulse-simple'
> --   Found libpulse-simple, version 13.99.1
> -- Cannot find soundio
> -- Checking for module 'jack'
> --   Found jack, version 1.9.12
> CMake Warning at CMakeLists.deps.txt:159 (message):
>   Cannot find library SDL2_image
> Call Stack (most recent call first):
>   CMakeLists.txt:55 (include)
> 
> 
> -- Checking for module 'glib-2.0'
> --   Found glib-2.0, version 2.64.6
> -- Checking for module 'gio-2.0'
> --   Found gio-2.0, version 2.64.6
> CMake Error at CMakeLists.deps.txt:175 (add_library):
>   add_library cannot create ALIAS target "sys::glib" because target
>   "PkgConfig::glib" is imported but not globally visible.
> Call Stack (most recent call first):
>   CMakeLists.txt:55 (include)
> 
> 
> CMake Error at CMakeLists.deps.txt:176 (add_library):
>   add_library cannot create ALIAS target "sys::gio" because target
>   "PkgConfig::gio" is imported but not globally visible.
> Call Stack (most recent call first):
>   CMakeLists.txt:55 (include)
> 
> 
> -- Checking for module 'libuv'
> --   Found libuv, version 1.34.2
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Configuring incomplete, errors occurred!
> See also "/home/anon/smf-dsp/build/CMakeFiles/CMakeOutput.log".
> See also "/home/anon/smf-dsp/build/CMakeFiles/CMakeError.log".
> 

Every dependency listed in README has been installed.

**Comment by jpcima** [comment]
Please try latest @ df3a6f3

**Comment by freq-mod** [comment]
Now it's OK, thanks!
