### ISSUE TITLE
MIDI instrument program names sometimes don't get displayed

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#24]
This bug affects mainly SC-88Pro MIDIs iirc. 
![bug](https://user-images.githubusercontent.com/32672779/110679778-c2b83e80-81cf-11eb-88e2-1abffdffe235.png)

Steps to replicate:
1. Just after starting the program, open any SC-88Pro .mid, for example [th.tar.gz](https://github.com/jpcima/smf-dsp/files/6118197/th.tar.gz).

**Comment by jpcima** [comment]
It's because a Roland reset is not recognized, I'll add it.
- this is the typical GS reset: "f0 41 10 42 12 40 00 7f 00 41 f7"
- the one that this file has: "F0 41 10 42 12 00 00 7F 00 01 F7"

The latter might be specific to SC88, I dont know for sure.

**Comment by jpcima** [comment]
added in 4877977

**Comment by freq-mod** [comment]
That fixed this problem, thanks!
