### ISSUE TITLE
[Feature request] Add option to disable automatic arpeggio on libADL/OPNMIDI

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#26]
libADLMDI and libOPNMDI were some time ago updated with ability to disable automatic arpeggio when MIDI playback uses more FM channels than the emulated chipset can provide. It allows cleaner playback -https://github.com/Wohlstand/libOPNMIDI/issues/101

**Comment by jpcima** [comment]
Synth plugins are updated and feature added in bdc5f45
Please check it.

**Comment by freq-mod** [comment]
Yes, it works fine. Thanks!
