### ISSUE TITLE
Add more GS MIDI resets

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#29]
The sequel to #24 - sometimes, MIDI program names still won't appear. 
[GSMIDI.zip](https://github.com/jpcima/smf-dsp/files/6642007/GSMIDI.zip) - contain a few examples of such songs. Most  of these _should_ be Edirol SD-20/SC-8820, however PASSPORT.MID and CANYON.MID... aren't they plain SC-55 songs? Why is one instrument name not recognized?

**Comment by jpcima** [comment]
These do not have an explicit reset.
The best way to handle these is that the software scans the file for programs to match them against the database, and use this information to detect the midi specification.

**Comment by jpcima** [comment]
Anyway, I should send systematically a reset before new tracks, because some of the synths have problems resetting with just the GM sequence.
So I'll do like this: if file lacks a reset sequence at the start, I'll scan the file to identify which MIDI spec it belongs to, and then I'll send the matching reset.

**Comment by jpcima** [comment]
This is supposed to be fixed in 00c609f.
Let me know if there are problems.

**Comment by freq-mod** [comment]
I would say it's OK, yet one minor problem: [MushiHS_Stage2.mid.zip](https://github.com/jpcima/smf-dsp/files/6647364/MushiHS_Stage2.mid.zip)

Channel 10 percussion set track name is blank, can anything de done about it?

**Comment by jpcima** [comment]
Done, the fall back will apply to percussion banks also

**Comment by freq-mod** [comment]
Thanks! If I find a song that can't fall back, I will reopen this issue.
