### ISSUE TITLE
Unable to build, cmake can't find SDL2 image that's present (Ubuntu 20.04)

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#35]
```
CMake Warning at CMakeLists.txt:72 (_message):
  Cannot find library SDL2_image
Call Stack (most recent call first):
  CMakeLists.deps.txt:174 (message)
  CMakeLists.txt:75 (include)
```
```
sudo apt install libsdl2-dev
[...]
libsdl2-dev is already the newest version (2.0.10+dfsg1-3).
```

**Comment by freq-mod** [comment]
@jpcima README file must be updated with adding two dependencies: `libaprutil1-dev` and `libsdl2-image-dev`

**Comment by jpcima** [comment]
`SDL2_image` is a separate library. Try `libsdl2-image-dev`.

You have the full list here
https://github.com/jpcima/smf-dsp/blob/a0c9a5a07e8406954212648d4a165c15c5d4f0eb/.github/workflows/build.yml#L17-L27

**Comment by jpcima** [comment]
Good remark, readme needs an update.
A thing to note: apr-util is only required if Glib<2.66, then it's a substitute for URI parsing API.
