### ISSUE TITLE
Windows build from GHA doesn't work

### ISSUE THREAD

**Issue by freq-mod** [jpcima/smf-dsp#37]
On startup, error message shows up:
`Entry Point Not Found _ZSt14_once_functor in library` \pathtosmfdsp`\icuuc70.dll`

File is present in the folder. OS is Windows 10 Enterprise 21H2 x64.

**Comment by jpcima** [comment]
Some ABI incompatibility with libstdc++ runtime, so it seems.
The simpler long term option would be migrating the build to windows vm with msys2.

**Comment by jpcima** [comment]
This is fixed.

**Comment by freq-mod** [comment]
thanks
