### ISSUE TITLE
[WINDOWS] stops responding to keys and does stuff at random? (also can't close the program)

### ISSUE THREAD

**Issue by soulware1** [jpcima/smf-dsp#40]
uhhhh it just stops responding to my keys and starts doing its own thing i guess

**Comment by imadeagithubaccountforthis** [comment]
okay it's acting like the x button is the back button and spamming it enough makes it fade to black and close?

**Comment by soulware1** [comment]
alright its just really delayed, changing the window scale somehow fixes it???
